// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using efdemo;

#nullable disable

namespace EFDemo.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20240501234648_TareasFix1")]
    partial class TareasFix1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("efdemo.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("990f2aab-3833-404d-bc2d-878096fadb03"),
                            Descripcion = "llll",
                            Nombre = "Actividades pendientes"
                        },
                        new
                        {
                            CategoriaId = new Guid("4147cfc2-63f8-412e-b89c-5583776da0e2"),
                            Descripcion = "mmmmmm",
                            Nombre = "Actividades personales"
                        });
                });

            modelBuilder.Entity("efdemo.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Pesos")
                        .HasColumnType("int");

                    b.Property<string>("PrioridadTarea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("fe2de405-c38e-4c90-ac52-da0540dfb410"),
                            CategoriaId = new Guid("4147cfc2-63f8-412e-b89c-5583776da0e2"),
                            Descripcion = "aaaa",
                            FechaCreacion = new DateTime(2024, 5, 1, 18, 46, 48, 231, DateTimeKind.Local).AddTicks(6846),
                            Pesos = 20,
                            PrioridadTarea = "Media",
                            Titulo = "Pago de servicios publicos"
                        },
                        new
                        {
                            TareaId = new Guid("fe2de405-c38e-4c90-ac53-da0540dfb411"),
                            CategoriaId = new Guid("4147cfc2-63f8-412e-b89c-5583776da0e2"),
                            Descripcion = "bbbb",
                            FechaCreacion = new DateTime(2024, 5, 1, 18, 46, 48, 231, DateTimeKind.Local).AddTicks(6860),
                            Pesos = 20,
                            PrioridadTarea = "Baja",
                            Titulo = "Terminar de ver pelicula en netflix"
                        });
                });

            modelBuilder.Entity("efdemo.Models.Tarea", b =>
                {
                    b.HasOne("efdemo.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("efdemo.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
